### ISSUE TITLE
1.3.0 regression - list of messages not shown

### ISSUE THREAD

**Issue by dilyanpalauzov** [GermanCoding/Roundcube_TLS_Icon#15]
I have PHP 8.1.16, Roundcube 1.16.1. and Roundcube_TLS_Icon 1.3.0.

If the function storage_init($p) has this body:
```php
        public function storage_init($p)
        {
                $headers = isset($p['fetch_headers']) ? $p['fetch_headers'] : '';
                $p['fetch_headers'] = trim($headers) . ' ' . strtoupper('Received');
                return $p;
        }
```
then the list of messages (in INBOX) does not load.  When I change to
```php
        public function storage_init($p)
        {
                $p['fetch_headers'] = trim(($p['fetch_headers']?? '') . ' ' . strtoupper('Received'));
                return $p;
        }
```
the list of messages is displayed. As far as I can see, in the first implementation, $p['fetch_headers'] is set to ` RECEIVED` with a leading space, in the latter function body $p['fetch_headers'] is set to `RECEIVED`.

Defect introduced by https://github.com/GermanCoding/Roundcube_TLS_Icon/commit/973b91b2114a72ae2423c1ce5f4ccdfb669456a5 .

**Comment by GermanCoding** [comment]
Yeah, looks like we got that wrong. Could you verify whether the fix works for you? I believe you can pull a build directly from packagist:

`composer require germancoding/tls_icon:dev-too-many-spaces`

**Comment by dilyanpalauzov** [comment]
When is `$p['fetch_headers']` not supposed to be empty?

**Comment by GermanCoding** [comment]
When you have other plugins that also request non-default headers from Roundcube. I personally seem to have them on my instances, which is why I haven't caught this earlier - for me 1.3.0 works fine.
