### ISSUE TITLE
Not working for all mails

### ISSUE THREAD

**Issue by DAMIOSKIDEV** [GermanCoding/Roundcube_TLS_Icon#20]
I don't know if I've misconfigured the plugin (I'm not very comfortable with the configuration of Roundcube, Postfix, etc...) but of all my mails, none show that it uses an encrypted connection. I do have headers indicating that the mail uses a TLS protocol.

Here's an example:

```
Received: from damioski.de
    by h3005393.stratoserver.net with LMTP
    id yKsqAIpCn2QdDRkA5DZ6zQ
    (envelope-from <bounces+1849726-61f7-admin=damioski.de@mailserviceemailout1.namecheap.com>)
    for <admin@damioski.de>; Fri, 30 Jun 2023 23:00:58 +0200
Received: from o7.mailservice.namecheap.com (o7.mailservice.namecheap.com [168.245.28.209])
    (using TLSv1.3 with cipher TLS_AES_128_GCM_SHA256 (128/128 bits)
    key-exchange X25519 server-signature RSA-PSS (2048 bits) server-digest SHA256)
    (No client certificate requested)
    by damioski.de (Postfix) with ESMTPS id 4536747A26BA
    for <admin@damioski.de>; Fri, 30 Jun 2023 23:00:57 +0200 (CEST)
```

![image](https://github.com/GermanCoding/Roundcube_TLS_Icon/assets/45036197/a4be2546-fc0f-4b7a-9645-1a54b62ab296)

Configuration file:
```
$config['tls_icon_ignore_hops'] = 0;
```

**Comment by GermanCoding** [comment]
By default the plugin only looks at the last hop, which in your case appears to be local `LMTP` which is obviously unencrypted.

You will need to configure the plugin (https://github.com/GermanCoding/Roundcube_TLS_Icon/blob/master/config.inc.php.dist) by setting `$config['tls_icon_ignore_hops'] = 1;` so that it ignores your LMTP hop.

**Comment by DAMIOSKIDEV** [comment]
Thanks, it works

![image](https://github.com/GermanCoding/Roundcube_TLS_Icon/assets/45036197/5bd77ed8-c528-42c2-b6f8-1cc61b10a352)
